# Copyright (c) 2021, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#

ARG BASE_VERSION=9.1.0-2.2.2
FROM container-registry.oracle.com/mysql/community-operator:$BASE_VERSION
COPY mysqloperator/ /usr/lib/mysqlsh/python-packages/

